apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 5000
  type: ClusterIP
